{% set version = "0.2" %}

package:
  name: amostra
  version: {{ version }}
  sha256: f6c4c0ad850c6c8907daf40cf078bd97883d1d424c88cb084fd79ef096fbc1c0

source:
  git_url: https://github.com/nsls-ii/amostra
  git_rev: v{{ version }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - doct
    - jsonschema
    - mongoquery
    - pymongo
    - requests
    - tornado
    - ujson
    - pyyaml

test:
  imports:
    - amostra
    - amostra.test
    - amostra.client
    - amostra.server
    - amostra.sample_data

about:
  home: https://nsls-ii.github.io/amostra
  license: BSD 3-Clause
  license_file: LICENSE
  summary: "amostra is a collection of light-weight sample management classes"

extra:
  recipe-maintainers:
    - ericdill
    - tacaswell
    - licode
